# Generated by Django 4.0.6 on 2022-11-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_content_product_image_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
